#!/bin/csh -f

if ($#argv != 3) then
  echo 'usage:'
  echo '$1 the window width'
  echo '$2 the averaging method a for mean, m for median'
  echo '$3 the file name prefix'
  exit
endif


tool/sm $1 $2 $3
am $3.$1.$2
rm -f $3.$1.$2.desc $3.$1.$2.bin
